version: '2'

services:
  postgres:
    container_name: "postgres"
    image: postgres:13.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres